services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "4567:80"
        environment:
            - APP_KEY=${APP_KEY}
            - DB_CONNECTION=sqlite
            - DB_DATABASE=/var/www/html/database/database.sqlite
            - CACHE_DRIVER=file
            - VIEW_COMPILED_PATH=/var/www/html/storage/framework/views
            - TRMNL_PROXY_REFRESH_MINUTES=15
        volumes:
            - ./database/database.sqlite:/var/www/html/database/database.sqlite
            - ./storage/logs:/var/www/html/storage/logs
            - ./storage/app:/var/www/html/storage/app
        restart: unless-stopped
        #platform: "linux/arm64/v8"
