version: "3.9"
services:
  cli:
    build: cli
    volumes:
      - ..:/workspaces/laravel

  fpm:
    build: fpm
    volumes:
      - ..:/workspaces/laravel
    user: 1000:1000

  nginx:
    build: nginx
    volumes:
      - ..:/workspaces/laravel
    ports:
      - 8080:80
    depends_on:
      - fpm
